### ISSUE TITLE
Fatal Flaw report from theme-customizations may be cause of sudden inability to update any plugins

### ISSUE THREAD

**Issue by cetgueli** [woothemes/theme-customisations#40]
Fatal error: Uncaught Error: Call to undefined function create_function() in /home/painti21/public_html/wp-content/plugins/theme-customisations-master/custom/functions.php:35

Ran updates on 29 July 2024.
Website functions well after updates but learned later unable to unable to run any plugin updates; first discovered 02 August.
Suspect, but do not know, that woocommerce/theme-customizations plugin is not compatible with one of the updates. 
The updates:

WP 6.5.5 to 6.6.1 - update and core files read good according to my WHM

WooCommerce 9.1.2 to 9.1.4

WooCommerce Stripe Gateway 8.5.1 to 8.5.2

Astra Theme 4.7.3

CTX Feed 6.5.7 to 6.5.9

WP File manager 7.2.9 to 7.2.10

Duplicator 1.5.10 to 9.1.4

WP Staging 3.8.1 to 3.8.3

Note: Have done so, but not normally familiar with delving into code. I can follow to a degree.

Full Script:
Fatal error: Uncaught Error: Call to undefined function create_function() in /home/painti21/public_html/wp-content/plugins/theme-customisations-master/custom/functions.php:35
Stack trace:
#0 /home/painti21/public_html/wp-content/plugins/theme-customisations-master/theme-customisations.php(34): require_once()
#1 /home/painti21/public_html/wp-content/plugins/theme-customisations-master/theme-customisations.php(111): Theme_Customisations->__construct()
#2 /home/painti21/public_html/wp-includes/class-wp-hook.php(324): theme_customisations_main('')
#3 /home/painti21/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#4 /home/painti21/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /home/painti21/public_html/wp-settings.php(555): do_action('plugins_loaded')
#6 phar:///usr/local/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1349): require('/home/painti21/...')
#7 phar:///usr/local/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1267): WP_CLI\Runner->load_wordpress()
#8 phar:///usr/local/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#9 phar:///usr/local/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#10 phar:///usr/local/bin/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#11 phar:///usr/local/bin/wp-cli.phar/php/boot-phar.php(20): include('phar:///usr/loc...')
#12 /usr/local/bin/wp-cli.phar(4): include('phar:///usr/loc...')
#13 {main}
  thrown in /home/painti21/public_html/wp-content/plugins/theme-customisations-master/custom/functions.php on line 35 

Many thanks for any help or direction!

**Comment by cetgueli** [comment]
UPDATE! Plugins can be updated but only through WP Admin. the issue was primarily that access was not being allowed to files from outside. May have something to do with xlmrpc.php
Yes, there is a fatal error displayed (4 actually) all linked to theme-customisations-master but do not know yet how the error is affecting access or if it is causing aa different issue somewhere else.

**Comment by jagku** [comment]
Hi,  Sorry - I have migrating a wordpress site to another server but this plugin is causing the site not to load.
I think it is caused by the PHP version being later.  Can I ask, do I just download all the files and zip them up.  Then install that zip file as a plugin.  I have version 1 currently installed
